### ISSUE TITLE
Fortify plugin: UnboundLocalError: local variable 'step' referenced before assignment

### ISSUE THREAD

**Issue by llazzaro** [infobyte/faraday_plugins#1]
```
Traceback (most recent call last):
  File "/Users/lcubo/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/lcubo/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/lcubo/workspace/faraday-plugins/faraday_plugins/__main__.py", line 66, in <module>
    cli()
  File "/Users/lcubo/.pyenv/versions/faradaypy3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lcubo/.pyenv/versions/faradaypy3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/lcubo/.pyenv/versions/faradaypy3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lcubo/.pyenv/versions/faradaypy3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lcubo/.pyenv/versions/faradaypy3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/lcubo/workspace/faraday-plugins/faraday_plugins/__main__.py", line 44, in process
    plugin.processReport(report_file)
  File "/Users/lcubo/workspace/faraday-plugins/faraday_plugins/plugins/plugin.py", line 173, in processReport
    self._parse_filename(filepath)
  File "/Users/lcubo/workspace/faraday-plugins/faraday_plugins/plugins/plugin.py", line 169, in _parse_filename
    self.parseOutputString(output.read())
  File "/Users/lcubo/workspace/faraday-plugins/faraday_plugins/plugins/repo/fortify/plugin.py", line 78, in parseOutputString
    fp = FortifyParser(output)
  File "/Users/lcubo/workspace/faraday-plugins/faraday_plugins/plugins/repo/fortify/plugin.py", line 104, in __init__
    self._extract_vulns()
  File "/Users/lcubo/workspace/faraday-plugins/faraday_plugins/plugins/repo/fortify/plugin.py", line 283, in _extract_vulns
    self._process_webinspect()
  File "/Users/lcubo/workspace/faraday-plugins/faraday_plugins/plugins/repo/fortify/plugin.py", line 247, in _process_webinspect
    service_data['name'] = step.Url.text
UnboundLocalError: local variable 'step' referenced before assignment
```

**Comment by llazzaro** [comment]
Solved at commit f982684c4e4e8ed65a50aec09223ac92c91ea098
