### ISSUE TITLE
nmap importing error

### ISSUE THREAD

**Issue by s0i37** [infobyte/faraday_plugins#4]
Hello.
After running `faraday-server` and `faraday-client` I'm trying to import results from simple nmap scan:
`nmap -Pn -n -oX 1.xml -p 445 10.0.0.64`

I make import as:
`cp 1.xml ~/.faraday/report/test/`

After that I obtain the following error:
```
2020-11-21T22:35:59+0500 - faraday_client.managers.reports_managers - INFO {ReportManagerThread} [reports_managers.py:99 - sendReport()]  The file is /home/soier/.faraday/report/test/1.xml, nmap
2020-11-21T22:35:59+0500 - faraday_client.plugins.controller - INFO {ReportManagerThread} [controller.py:256 - processReport()]  Processing report with plugin nmap
2020-11-21T22:35:59+0500 - faraday_client.managers.reports_managers - ERROR {ReportManagerThread} [reports_managers.py:140 - run()]  An exception was captured while saving reports
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/faraday_client-1.0.0-py3.7.egg/faraday_client/managers/reports_managers.py", line 136, in run
    self.syncReports()
  File "/usr/local/lib/python3.7/dist-packages/faraday_client-1.0.0-py3.7.egg/faraday_client/managers/reports_managers.py", line 162, in syncReports
    if self.processor.processReport(filename) is False:
  File "/usr/local/lib/python3.7/dist-packages/faraday_client-1.0.0-py3.7.egg/faraday_client/managers/reports_managers.py", line 95, in processReport
    return self.sendReport(plugin.id.lower(), filename)
  File "/usr/local/lib/python3.7/dist-packages/faraday_client-1.0.0-py3.7.egg/faraday_client/managers/reports_managers.py", line 100, in sendReport
    command_id = self.plugin_controller.processReport(plugin_id, filename, ws_name=self.ws_name)
  File "/usr/local/lib/python3.7/dist-packages/faraday_client-1.0.0-py3.7.egg/faraday_client/plugins/controller.py", line 259, in processReport
    self.processOutput(plugin, output.read(), cmd_info, True)
  File "/usr/local/lib/python3.7/dist-packages/faraday_client-1.0.0-py3.7.egg/faraday_client/plugins/controller.py", line 125, in processOutput
    plugin.processOutput(output.decode('utf8'))
  File "/usr/local/lib/python3.7/dist-packages/faraday_plugins/plugins/plugin.py", line 283, in processOutput
    self.parseOutputString(command_output)
  File "/usr/local/lib/python3.7/dist-packages/faraday_plugins/plugins/repo/nmap/plugin.py", line 459, in parseOutputString
    parser = NmapXmlParser(output)
  File "/usr/local/lib/python3.7/dist-packages/faraday_plugins/plugins/repo/nmap/plugin.py", line 42, in __init__
    tree = self.parse_xml(xml_output)
  File "/usr/local/lib/python3.7/dist-packages/faraday_plugins/plugins/repo/nmap/plugin.py", line 61, in parse_xml
    return etree.parse(BytesIO(xml_output), magical_parser)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by aenima-x** [comment]
@s0i37 sorry for the delay.
Can you tell me if you still have this problem?

**Comment by fedek** [comment]
This issue seems to be solved. Thanks for the feedback.
